-- ISO 3166-1 alpha-2 reference data (not university catalog facts).
INSERT INTO public.countries (code, name, supported) VALUES
('AD', 'Andorra', true),
('AE', 'United Arab Emirates', true),
('AF', 'Afghanistan', true),
('AG', 'Antigua and Barbuda', true),
('AI', 'Anguilla', true),
('AL', 'Albania', true),
('AM', 'Armenia', true),
('AO', 'Angola', true),
('AQ', 'Antarctica', true),
('AR', 'Argentina', true),
('AS', 'American Samoa', true),
('AT', 'Austria', true),
('AU', 'Australia', true),
('AW', 'Aruba', true),
('AZ', 'Azerbaijan', true),
('BA', 'Bosnia and Herzegovina', true),
('BB', 'Barbados', true),
('BD', 'Bangladesh', true),
('BE', 'Belgium', true),
('BF', 'Burkina Faso', true),
('BG', 'Bulgaria', true),
('BH', 'Bahrain', true),
('BI', 'Burundi', true),
('BJ', 'Benin', true),
('BM', 'Bermuda', true),
('BN', 'Brunei Darussalam', true),
('BO', 'Bolivia', true),
('BR', 'Brazil', true),
('BS', 'Bahamas', true),
('BT', 'Bhutan', true),
('BW', 'Botswana', true),
('BY', 'Belarus', true),
('BZ', 'Belize', true),
('CA', 'Canada', true),
('CD', 'Congo (Democratic Republic)', true),
('CF', 'Central African Republic', true),
('CG', 'Congo', true),
('CH', 'Switzerland', true),
('CI', 'Côte d’Ivoire', true),
('CK', 'Cook Islands', true),
('CL', 'Chile', true),
('CM', 'Cameroon', true),
('CN', 'China', true),
('CO', 'Colombia', true),
('CR', 'Costa Rica', true),
('CU', 'Cuba', true),
('CV', 'Cabo Verde', true),
('CY', 'Cyprus', true),
('CZ', 'Czechia', true),
('DE', 'Germany', true),
('DJ', 'Djibouti', true),
('DK', 'Denmark', true),
('DM', 'Dominica', true),
('DO', 'Dominican Republic', true),
('DZ', 'Algeria', true),
('EC', 'Ecuador', true),
('EE', 'Estonia', true),
('EG', 'Egypt', true),
('EH', 'Western Sahara', true),
('ER', 'Eritrea', true),
('ES', 'Spain', true),
('ET', 'Ethiopia', true),
('FI', 'Finland', true),
('FJ', 'Fiji', true),
('FK', 'Falkland Islands', true),
('FM', 'Micronesia', true),
('FO', 'Faroe Islands', true),
('FR', 'France', true),
('GA', 'Gabon', true),
('GB', 'United Kingdom', true),
('GD', 'Grenada', true),
('GE', 'Georgia', true),
('GF', 'French Guiana', true),
('GG', 'Guernsey', true),
('GH', 'Ghana', true),
('GI', 'Gibraltar', true),
('GL', 'Greenland', true),
('GM', 'Gambia', true),
('GN', 'Guinea', true),
('GP', 'Guadeloupe', true),
('GQ', 'Equatorial Guinea', true),
('GR', 'Greece', true),
('GT', 'Guatemala', true),
('GU', 'Guam', true),
('GW', 'Guinea-Bissau', true),
('GY', 'Guyana', true),
('HK', 'Hong Kong', true),
('HN', 'Honduras', true),
('HR', 'Croatia', true),
('HT', 'Haiti', true),
('HU', 'Hungary', true),
('ID', 'Indonesia', true),
('IE', 'Ireland', true),
('IL', 'Israel', true),
('IM', 'Isle of Man', true),
('IN', 'India', true),
('IQ', 'Iraq', true),
('IR', 'Iran', true),
('IS', 'Iceland', true),
('IT', 'Italy', true),
('JE', 'Jersey', true),
('JM', 'Jamaica', true),
('JO', 'Jordan', true),
('JP', 'Japan', true),
('KE', 'Kenya', true),
('KG', 'Kyrgyzstan', true),
('KH', 'Cambodia', true),
('KI', 'Kiribati', true),
('KM', 'Comoros', true),
('KN', 'Saint Kitts and Nevis', true),
('KP', 'Korea (Democratic People''s Republic)', true),
('KR', 'Korea (Republic)', true),
('KW', 'Kuwait', true),
('KY', 'Cayman Islands', true),
('KZ', 'Kazakhstan', true),
('LA', 'Lao People''s Democratic Republic', true),
('LB', 'Lebanon', true),
('LC', 'Saint Lucia', true),
('LI', 'Liechtenstein', true),
('LK', 'Sri Lanka', true),
('LR', 'Liberia', true),
('LS', 'Lesotho', true),
('LT', 'Lithuania', true),
('LU', 'Luxembourg', true),
('LV', 'Latvia', true),
('LY', 'Libya', true),
('MA', 'Morocco', true),
('MC', 'Monaco', true),
('MD', 'Moldova', true),
('ME', 'Montenegro', true),
('MG', 'Madagascar', true),
('MH', 'Marshall Islands', true),
('MK', 'North Macedonia', true),
('ML', 'Mali', true),
('MM', 'Myanmar', true),
('MN', 'Mongolia', true),
('MO', 'Macao', true),
('MP', 'Northern Mariana Islands', true),
('MQ', 'Martinique', true),
('MR', 'Mauritania', true),
('MS', 'Montserrat', true),
('MT', 'Malta', true),
('MU', 'Mauritius', true),
('MV', 'Maldives', true),
('MW', 'Malawi', true),
('MX', 'Mexico', true),
('MY', 'Malaysia', true),
('MZ', 'Mozambique', true),
('NA', 'Namibia', true),
('NC', 'New Caledonia', true),
('NE', 'Niger', true),
('NG', 'Nigeria', true),
('NI', 'Nicaragua', true),
('NL', 'Netherlands', true),
('NO', 'Norway', true),
('NP', 'Nepal', true),
('NR', 'Nauru', true),
('NU', 'Niue', true),
('NZ', 'New Zealand', true),
('OM', 'Oman', true),
('PA', 'Panama', true),
('PE', 'Peru', true),
('PF', 'French Polynesia', true),
('PG', 'Papua New Guinea', true),
('PH', 'Philippines', true),
('PK', 'Pakistan', true),
('PL', 'Poland', true),
('PM', 'Saint Pierre and Miquelon', true),
('PN', 'Pitcairn', true),
('PR', 'Puerto Rico', true),
('PS', 'Palestine, State of', true),
('PT', 'Portugal', true),
('PW', 'Palau', true),
('PY', 'Paraguay', true),
('QA', 'Qatar', true),
('RE', 'Réunion', true),
('RO', 'Romania', true),
('RS', 'Serbia', true),
('RU', 'Russian Federation', true),
('RW', 'Rwanda', true),
('SA', 'Saudi Arabia', true),
('SB', 'Solomon Islands', true),
('SC', 'Seychelles', true),
('SD', 'Sudan', true),
('SE', 'Sweden', true),
('SG', 'Singapore', true),
('SH', 'Saint Helena', true),
('SI', 'Slovenia', true),
('SK', 'Slovakia', true),
('SL', 'Sierra Leone', true),
('SM', 'San Marino', true),
('SN', 'Senegal', true),
('SO', 'Somalia', true),
('SR', 'Suriname', true),
('SS', 'South Sudan', true),
('ST', 'Sao Tome and Principe', true),
('SV', 'El Salvador', true),
('SX', 'Sint Maarten', true),
('SY', 'Syrian Arab Republic', true),
('SZ', 'Eswatini', true),
('TC', 'Turks and Caicos Islands', true),
('TD', 'Chad', true),
('TG', 'Togo', true),
('TH', 'Thailand', true),
('TJ', 'Tajikistan', true),
('TK', 'Tokelau', true),
('TL', 'Timor-Leste', true),
('TM', 'Turkmenistan', true),
('TN', 'Tunisia', true),
('TO', 'Tonga', true),
('TR', 'Türkiye', true),
('TT', 'Trinidad and Tobago', true),
('TV', 'Tuvalu', true),
('TW', 'Taiwan', true),
('TZ', 'Tanzania', true),
('UA', 'Ukraine', true),
('UG', 'Uganda', true),
('US', 'United States', true),
('UY', 'Uruguay', true),
('UZ', 'Uzbekistan', true),
('VA', 'Holy See', true),
('VC', 'Saint Vincent and the Grenadines', true),
('VE', 'Venezuela', true),
('VG', 'Virgin Islands (British)', true),
('VI', 'Virgin Islands (U.S.)', true),
('VN', 'Viet Nam', true),
('VU', 'Vanuatu', true),
('WF', 'Wallis and Futuna', true),
('WS', 'Samoa', true),
('YE', 'Yemen', true),
('YT', 'Mayotte', true),
('ZA', 'South Africa', true),
('ZM', 'Zambia', true),
('ZW', 'Zimbabwe', true)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, supported = EXCLUDED.supported;
